# File: virtual_geofence/config/boundary.yaml
geofence_node:
  ros__parameters:
    boundary_coords:
      - 51.507481
      - -0.127959
      - 51.507481
      - -0.127641
      - 51.507319
      - -0.127641
      - 51.507319
      - -0.127959
    kalman_process_noise: 0.01
    kalman_measurement_noise: 2.5
