# File: virtual_geofence/config/boundary.yaml
geofence_node:
  ros__parameters:
    # put lat,lon pairs in this order: lat1, lon1, lat2, lon2, ...
    boundary_coords: [7.5200, 4.5180, 7.5210, 4.5180, 7.5210, 4.5190, 7.5200, 4.5190]
    kalman_process_noise: 0.01
    kalman_measurement_noise: 2.5
